### ISSUE TITLE
JClic doesn't run in Fedora 32 beta with Wayland: No X11 DISPLAY variable was set

### ISSUE THREAD

**Issue by jgarciao** [flathub/cat.xtec.clic.JClic#1]
Hi Ismael. First of all thanks a lot for packaging JClic. I know this app from a long time when I worked in a high school in the IT dept and now I was trying to show it to my kids

I'm afraid it's not working on Fedora 32 Beta with Wayland:
```
$ flatpak run cat.xtec.clic.JClic 
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at edu.xtec.jclic.SingleInstanceJFrame.<init>(SingleInstanceJFrame.java:62)
	at JClicPlayer.main(JClicPlayer.java:35)
```

**Comment by jgarciao** [comment]
In the same computer using with regular X11  the app seems to work fine

**Comment by olea** [comment]
This seems to be a non-trivial javafx bug since there [is not a Wayland backend for JavaFX](https://lists.freedesktop.org/archives/wayland-devel/2016-August/030832.html) ready. 

I found [this post at Stackoverflow](https://stackoverflow.com/questions/39197208/java-gui-support-on-wayland). I understand [the bug would have been fixed in openjdk in 2016](http://mail.openjdk.java.net/pipermail/caciocavallo-dev/2016-August/000558.html) but I made a build with the last opendk extension available and still not work:

```
$ flatpak-builder --run build-dir  cat.xtec.clic.JClic.yml jclic
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:165)
        at java.desktop/java.awt.Window.<init>(Window.java:540)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at edu.xtec.jclic.SingleInstanceJFrame.<init>(SingleInstanceJFrame.java:62)
        at JClicPlayer.main(JClicPlayer.java:35)
$ cat build-dir/files/jre/release 
IMPLEMENTOR="N/A"
JAVA_VERSION="14"
JAVA_VERSION_DATE="2020-03-17"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.namin
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=""
```
Sorry for asking you @mbooth101 but maybe you could give us more light, could you?

**Comment by jgarciao** [comment]
Ismael, if I run sh inside the sandbox and then run the app I have the same problem:
```
$ flatpak run  --command=/bin/sh cat.xtec.clic.JClic
[📦 cat.xtec.clic.JClic ~]$ /app/bin/jclic
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/java.awt.Frame.<init>(Frame.java:388)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at edu.xtec.jclic.SingleInstanceJFrame.<init>(SingleInstanceJFrame.java:62)
	at JClicPlayer.main(JClicPlayer.java:35)
```

But if inside the sandox I run `export DISPLAY=:0.0` then the app works fine:
```
[📦 cat.xtec.clic.JClic ~]$ export DISPLAY=:0.0
[📦 cat.xtec.clic.JClic ~]$ /app/bin/jclic
```

So, maybe you could set DISPLAY at /app/bin/jclic and /app/bin/jclicauthor

**Comment by mbooth101** [comment]
> ```
> No X11 DISPLAY variable was set,
> ```
> 
> Sorry for asking you @mbooth101 but maybe you could give us more light, could you?

Maybe I'm stating the obvious, but you are trying to use X11 but you don't set ```--socket=x11``` in your "finish-args" .... This is not specifically a Java problem -- you always have to allow the sandbox access to X11 if your app requires it.

The option ```--socket=fallback-x11``` only opens the X11 socket if there is no Wayland socket, so if your app does not support Wayland then it will fail when Wayland ***is*** available.

Clearly this app does not support Wayland, so you must specify ```--socket=x11``` instead.

**Comment by jgarciao** [comment]
I can confirm that removing wayland and fallback-x11 and adding x11 the app works fine. Thanks @mbooth101 

```
sudo flatpak override --nosocket=wayland --nosocket=fallback-x11  --socket=x11  cat.xtec.clic.JClic 
flatpak run cat.xtec.clic.JClic
```

**Comment by olea** [comment]
> Clearly this app does not support Wayland, so you must specify `--socket=x11` instead.

my fault :-/

Changed the sockets configuration, checked with openjdk11 in wayland and X11 and everything seems to be right.

The bundle update is being published right now.

Thanks @jgarciao for reporting and @mbooth101 for the tip!

**Comment by jgarciao** [comment]
Thanks to you Ismael!

El dc., 22 d’abr. 2020, 19:36, Ismael Olea <notifications@github.com> va
escriure:
